// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1SL9kKEfkeDaOrrEsY_yDxw7qMJlHLJY',
    appId: '1:561783417405:web:6f5addde1d6c18a1711854',
    messagingSenderId: '561783417405',
    projectId: 'stay-389401',
    authDomain: 'stay-389401.firebaseapp.com',
    storageBucket: 'stay-389401.appspot.com',
    measurementId: 'G-M9Y829C32M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1tENbPAe4U4wV_2KNT6kGXvSxdoRSt58',
    appId: '1:561783417405:android:7a2b14499f68e874711854',
    messagingSenderId: '561783417405',
    projectId: 'stay-389401',
    storageBucket: 'stay-389401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdx-c54mUfpSodaP1ocZMbFEO6iPmdIw',
    appId: '1:561783417405:ios:8cd629fcf62bcdb8711854',
    messagingSenderId: '561783417405',
    projectId: 'stay-389401',
    storageBucket: 'stay-389401.appspot.com',
    iosClientId: '561783417405-t3r4mf0bvsielefgdcmah8jgofq5irrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayCurrentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAdx-c54mUfpSodaP1ocZMbFEO6iPmdIw',
    appId: '1:561783417405:ios:c496b4fc27187d15711854',
    messagingSenderId: '561783417405',
    projectId: 'stay-389401',
    storageBucket: 'stay-389401.appspot.com',
    iosClientId: '561783417405-c10hn2luaf6pv5dnvjk51scosf1gd4ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayCurrentFlutter.RunnerTests',
  );
  
}

