name: stay_current_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-199.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Oleo_Script
      fonts:
        - asset: assets/fonts/Oleo_Script/OleoScript-Regular.ttf
        - asset: assets/fonts/Oleo_Script/OleoScript-Bold.ttf
          weight: 700
